os:
  -linux

language:
  - bash

before_script:
  - sudo easy_install bashtest
  - sudo chmod +x ./diskhog.sh
  - sudo apt-get install locate
  - sudo mkdir ./sql
  - sudo mkdir ./txt
  - sudo fallocate -l 250M ./sql/250M.sql
  - sudo fallocate -l 250M ./txt/250M.txt
  - sudo fallocate -l 50M ./sql/50M.sql
  - sudo fallocate -l 50M ./txt/50M.txt
  - sudo stat /var/lib/mlocate/mlocate.db
  - sudo ./diskhog.sh --fastest 50
  - sudo ./diskhog.sh --faster 50
  - sudo ./diskhog.sh --fast 250
  - sudo ./diskhog.sh --slow 250
  

script:
  - bashtest ./test/fastest_test.bashtest
  - bashtest ./test/faster_test.bashtest
  - bashtest ./test/fast_test.bashtest
  - bashtest ./test/slow_test.bashtest

